#!/usr/bin/env bash
# Transfer a file to your sever
# Usage: ./this_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY

if [[ $# -lt 3 ]];
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi
