#!/usr/bin/env bash
# Transfer a file to the home directory of your sever
# Usage: ./this_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY

if [[ $# -lt 4 ]];
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

PATH_TO_FILE=$1
IP=$2
USERNAME=$3
PATH_TO_SSH_KEY=$4

scp -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "$USERNAME"@"$IP":~/
