#!/usr/bin/env bash
# Automate - installation and configuration of an Ubuntu macine to for nginx server
# Ensure to use 'sudo' previleges if you are not a super user

default_index='/var/www/html/index.nginx-debian.html'

# Install nginx server
apt-get -y install nginx

# Set ufw status - Adjust the Firewal
ufw allow 'Nginx HTTP'

# Create landing page
echo 'Hello World!' > "$default_index"

# Restart service
service nginx start
