#!/usr/bin/env bash
# Automate - installation and configuration of an Ubuntu machine to for nginx server
# Ensure to use 'sudo' previleges if you are not a super user

default_index='/var/www/html/index.nginx-debian.html'
SITE='/var/www/html/'
server_config='/etc/nginx/sites-enabled/default'
server_config_temp='./server_config_3'

# Install nginx server
apt-get -y update
apt-get -y install nginx

# Set ufw status - Adjust the Firewal
ufw allow 'Nginx HTTP'

# Configure user to own site
chown -R "$USER":"$USER" "$SITE"

# Create landing page
echo 'Hello World!' > "$default_index"

# Configure server
cp "$server_config_temp" "$server_config"

# Restart service
service nginx restart
