#!/usr/bin/env bash
# Automate - installation and configuration of an Ubuntu machine to for nginx server
# Ensure to use 'sudo' previleges if you are not a super user

default_index='/var/www/html/index.html'
SITE='/var/www/html/'
server_config='/etc/nginx/sites-enabled/default'
# server_config_temp='./server_config_3'

# Install nginx server
apt-get -y update
apt-get -y install nginx

# Set ufw status - Adjust the Firewal
ufw allow 'Nginx HTTP'

# Configure user to own site
chown -R "$USER":"$USER" "$SITE"

# Create landing page
echo 'Hello World!' > "$default_index"

# Configure server
# cp "$server_config_temp" "$server_config"
# shellcheck disable=SC2016
echo 'server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /var/www/html;

	# Add index
	index index.html

	server_name _;

	location / {
		# Fist attempt to server a request as file, then
		# as directory, then fall back to displaying a 404 error.
		try_files $uri $uri/ =404;
	}

	location /redirect_me {
		# Have fun with redirection
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}
}' > "$server_config"

# Restart service
service nginx restart
