#!/usr/bin/env bash
# Automate - installation and configuration of an Ubuntu macine to for nginx server
# Ensure to use 'sudo' previleges if you are not a super user

default_index='/var/www/html/index.nginx-debian.html'
SITE='var/www/html'
server_config='/etc/nginx/sites-available/default'

# Install nginx server
apt-get -y install nginx

# Set ufw status - Adjust the Firewal
ufw allow 'Nginx HTTP'

# Configure server
# shellcheck disable=SC2016
echo 'server {
	listen 80 default_server:
	listen [::]:80 default_server;

	root /var/www/html;

	# Add index
	index index.html

	server_name _;

	location / {
		# First attempt to serve request as file, then
		# as directory, then fall back to displaying a 404.
		try_files $uri $uri/ =404;
	}

	location /redirect_me {
		# redirect to another page - have fun
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}
}' > "$server_config"

# Configure user to own site
chown -R "$USER":"$USER" "$SITE"

# Create landing page
echo 'Hello World!' > "$default_index"

# Restart service
service nginx start
