#!/usr/bin/env bash
# Automate - installation and configuration of an ubuntu machine for nginx server
# It has a custome error page
# Ensure to use 'sudo' privileges if you are not a super user

SITE=/var/www/html
default_index="$SITE"/index.html
server_config=/etc/nginx/sites-enabled/default
error_page="$SITE"/404.html

# Install nginx server
apt-get --assume-yes update
apt-get --assume-yes install nginx

# Set Firewall
ufw allow 'Nginx HTTP'

# Configure user to own site
mkdir --parents "$SITE"
chown --recursive "$USER":"$USER" "$SITE"

# Create landing page
echo "Hello World!" > "$default_index"

# Create error page
echo "Ceci n'est pas une page
" > "$error_page"

# shellcheck disable=SC2016
echo '# CONFIGURATION FOR SERVER - ONWUTA EBUBE GIDEON
server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /var/www/html;

	# Include header in response
	add_header X-Server-By $hostname;

	# Add index
	index index.html

	server_name _;

	location / {
		# First attempt to server a request as file, then
		# as directory, then fall back to displaying a 404 ERROR
		try_files $uri $uri/ =404;
	}

	location /redirect_me {
		# Have fun with redirection
		rewrite ^/redirect_me(.*)$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
	}

	# Create a custom 404 error page
	error_page 404 /404.html;
	location = /404.html {
		# To ensure it cannot be accessed directly by clients
		internal;
	}
}' > "$server_config"

# Restart service
service nginx restart
