#!/usr/bin/env bash
# A script to manage the ``manage_my_process`` process

my_process="manage_my_process"
my_ppid="/var/run/my_process.pid"


# Check for excess or deficit command line arguments
if [ "$#" -ne 1 ]
then
	echo "Usage: $my_process {start|stop|restart}"
	exit $?
fi

# Check for inappropriate commands
if [ "$1" -ne "start" ] -o [ "$1" -ne "stop" ] -o [ "$1" -ne "restart" ]
then
	echo "Usage: $my_process {start|stop|restart}"
	exit $?
fi


# Interpret commmands
if [ "${1}" == "start" ]
then
	./"$my_process" &	# start this process in the background
	echo "$!" > "$my_ppid"
	echo "$my_process started"
elif [ "${1}" == "stop" ]
then
	kill "$(cat my_ppid)"
	rm "$my_ppid"
	echo "$my_process stopped"
elif [ "$1" == "restart" ]
then
	kill "$(cat my_ppid)"
	rm "my_ppid"
	./"$my_process" &
	echo "$!" > "$my_ppid"
	echo "$my_process restarted"
fi
