#!/usr/bin/env bash
#  A script that stops ``4-to_infinity_and_beyond`` process
#  shellcheck disable=SC2009
#  Flag ``-f`` means to refer to a process initiated by the command line given

my_pid=$(ps auxf | grep 7-highlander | grep bash | awk '{print $NF}')

if [ -n "$my_pid" ]
then
	pkill -15 -f "$my_pid"
fi
