#!/usr/bin/env bash
# A bash script that displays message indefinitely

message="I am invincible!!"

# Display this message on receiving SIGTERM signal
trap 'echo $message' TERM

while true; do
	echo "To infinity and beyond"
	sleep 2
done
