#!/usr/bin/env bash
# Write a Bash script that displays numbers from 1 to 100.
#
# Requirements:
#
#	Displays FizzBuzz when the number is a multiple of 3 and 5
#	Displays Fizz when the number is multiple of 3
#	Displays Buzz when the number is a multiple of 5
#	Otherwise, displays the number
#	In a list format

MAX=100
I=1

while [ $I -le $MAX ]; do
	if [ "$((I % 3))" -eq 0 ] && [ "$((I % 5))" -eq 0 ]; then
		echo "FizzBuzz"
	elif [ "$((I % 3))" -eq 0 ]; then
		echo "Fizz"
	elif [ "$((I % 5))" -eq 0 ]; then
		echo "Buzz"
	else
		echo "$I"
	fi
	I=$((I + 1))
done
