#!/usr/bin/env bash
# Run the FizzBuzz program
# Displays ``FizzBuzz`` when the number is a multiple of 3 and 5
# Displays ``Fizz`` when the number is a multiple of 3
# Displays ``Buzz`` when the number is a multiple of 5
# Otherwise, displays the number
# In a list format

for COUNT in {1..100}; do
	if [[ $((COUNT % 15)) -eq 0 ]]
	then
		echo "FizzBuzz"
	elif [[ $((COUNT % 3)) -eq 0 ]]
	then
		echo "Fizz"
	elif [[ $((COUNT % 5)) -eq 0 ]]
	then
		echo "Buzz"
	else
		echo "$COUNT"
	fi
done
