#!/usr/bin/env bash
# Run the FizzBuzz program
# Displays ``FizzBuzz`` when the number is a multiple of 3 and 5
# Displays ``Fizz`` when the number is a multiple of 3
# Displays ``Buzz`` when the number is a multiple of 5
# Otherwise, displays the number
# In a list format

for count in {1..100}; do
	if [[ $((count % 15)) -eq 0 ]]
	then
		echo "FizzBuzz"
	elif [[ $((count % 3)) -eq 0 ]]
	then
		echo "Fizz"
	elif [[ $((count % 5)) -eq 0 ]]
	then
		echo "Buzz"
	else
		echo "$count"
	fi
done
