#!/usr/bin/env bash
# Write a Bash script that displays the content of the file /etc/passwd.
#
# Your script should only display:
#
#	username
#	user id
#	Home directory path for the user
#
# Requirements:
#
#	You must use the while loop (for and until are forbidden)

EOF=0
FILE="/etc/passwd"

while [ $EOF == 0 ]; do
	read -r LINE
	EOF=$?
	if [ $EOF == 0 ]; then
		CONTENT=$( echo "$LINE" | cut --delimiter=':' --fields=1,3,6 )
		echo "$CONTENT"
	fi
done < "$FILE"
