#!/usr/bin/env bash
# Write a Bash script that displays the content of the file /etc/passwd.
#
# Your script should only display:
#
#	username
#	user id
#	Home directory path for the user
#
# Requirements:
#
#	You must use the while loop (for and until are forbidden)

FILE="/etc/passwd"

# shellcheck disable=SC2034
while IFS=':' read -r f1 f2 f3 f4 f5 f6 f7; do
	echo "$f1:$f3:$f6"
done < "$FILE"
