#!/usr/bin/env bash
#  Parse Apache log file using `awd`
#  This script groups visitors by ``IP`` and ``HTTP`` status code,
#+ and displays this data
#
#  The exact format must be:
#  * OCCURENCE_NUMBER IP HTTP_CODE
#  * In list format
#  * Ordered from the greatest to the lowest number of occurrences
#
#  In an apache log file, the column 1 and 9 are the IP and HTTP_CODE
#+ respectively

awk '{print $1" "$9}' apache-access.log | sort | uniq -c | sort -r -n
