#!/usr/bin/env bash
#  A Bash script that displays Best School 10 times,
#+ but for the 9th iteration, displays Best School and then Hi on a new line.

I=0
MAX=10
MSG="Best School"

while [[ $I -lt $MAX ]]; do
	echo "$MSG"
	if [[ $I -eq $((9 - 1)) ]]; then
		echo "Hi"
	fi
	I=$((I + 1))
done
