#!/usr/bin/env bash
# Examplifies the use of ``if``, ``elif``, and ``else`` statements

count=1

while [[ $count -le 10 ]]; do
	if [[ $count -eq 4 ]]
	then
		echo "bad luck"
	elif [[ $count -eq 8 ]]
	then
		echo "good luck"
	else
		echo "Best School"
	fi

	count=$((count + 1))
done
