#!/usr/bin/env bash
# Write a Bash script that loops from 1 to 10 and:
#
#	displays bad luck for the 4th loop iteration
#	displays good luck for the 8th loop iteration
#	displays Best School for the other iterations

I=1
MAX=10
MSG="Best School"

while [[ $I -le $MAX ]]; do
	if [[ $I -eq 4 ]]; then
		echo "bad luck"
	elif [[ $I -eq 8 ]]; then
		echo "good luck"
	else
		echo "$MSG"
	fi
	I=$((I + 1))
done
