#!/usr/bin/env bash
# Empplifies the use of `if`, `elif` and `else` statements

COUNT=0
PHRASE="Best School"

while [[ $COUNT -lt 10 ]]; do
	if [[ $COUNT -eq 4 ]]
	then
		echo "bad luck"
	elif [[ $COUNT -eq 8 ]]
	then
		echo "good luck"
	else
		echo "$PHRASE"
	fi

	COUNT=$((COUNT + 1))
done
