#!/usr/bin/env bash
# Makes use of the ``switch ... case`` statement

count=1

while [[ $count -le 20 ]]; do
	echo "$count"

	case $count in
	4)
		echo "bad luck from China";;
	9)
		echo "bad luck from Japan";;
	17)
		echo "bad luck from Italy";;
	esac

	count=$((count + 1))
done
