#!/usr/bin/env bash
# A script that displays the time for 12 hours and 59 minutes
#
#	display hours from 0 to 12
#	display minutes from 1 to 59

hour=12
minutes=60

x=0
while [[ $x -le hour ]]; do
	echo "Hour: $x"
	y=1
	while [[ $y -lt minutes ]]; do
		echo "$y"
		y=$((y + 1))
	done
	x=$((x + 1))
done
