#!/usr/bin/env bash
# A script that displays:
#	* The content of the current direectory
#	* In a list format
#	* Where only the part of the name after the first dash is displayd
# E.g
# ..$ ls
# 100-read_and_cut	1-for_best_school	10-fizzbuzz
# ..$ ./8-for_ls
# read_and_cut
# for_best_school
# fizzbuzz


for file in *; do
	file_to_print=$( echo "$file" | cut --delimiter='-' --fields=2 )
	echo "$file_to_print"
done
