#!/usr/bin/env bash
# Install Firewall; block all incoming traffic but allow ssh, https ssl and http
sudo apt-get --assume-yes update
sudo apt-get --assume-yes install ufw
sudo ufw default deny incoming -y
sudo ufw allow proto tcp from any to any port 22,443,80
sudo ufw enable -y
