#!/usr/bin/env bash
# Install Firewall; block all incoming traffic but allow ssh, https ssl and http
sudo apt-get --assume-yes update
sudo apt-get --assume-yes install ufw
sudo ufw --force reset
sudo ufw default deny incoming
sudo ufw allow in proto tcp from any to any port 22
sudo ufw allow in proto tcp from any to any port 443
sudo ufw allow in proto tcp from any to any port 80
sudo ufw --force enable
