#!/usr/bin/env bash
#  Configure an Ubuntu server with the below requirements:
#	* ``localhost`` resolves to ``127.0.0.2``
#	* ``facebook.com`` resolves to ``8.8.8.8``

cp /etc/hosts ~/hosts.new

#  Search for a line that contains ``localhost``, replace it with
#+ ``127.0.0.2	localhost/g``
sed -i "s/.*localhost$/127.0.0.2	localhost/g" ~/hosts.new

# Search and replace line if found
sed -i "s/.*facebook.com/8.8.8.8	facebook.com/g" ~/hosts.new

# append the line ``8.8.8.8	facebook.com/g`` to the file /etc
echo '8.8.8.8	facebook.com' >> ~/hosts.new


cp -f ~/hosts.new /etc/hosts
