#!/usr/bin/env bash
#  Configure an Ubuntu server with the below requirements:
#	* ``localhost`` resolves to ``127.0.0.2``
#	* ``facebook.com`` resolves to ``8.8.8.8``

cp /etc/hosts ~/hosts.new
str1="127.0.0.2	localhost"
str2="8.8.8.8	facebook.com"

sed -i "s/.*localhost$/127.0.0.2	localhost/g" ~/hosts.new

sed -i "s/.*facebook.com/8.8.8.8	facebook.com/g" ~/hosts.new
