#!/usr/bin/env bash
# Configure an Ubuntu server with the below requirements
# Requirements:
#	* 'localhost' resolves to '127.0.0.2'
#	* 'facebook.com' resolves to '8.8.8.8'

HOSTS='/etc/hosts'
HOSTS_OLD='/etc/hosts.old'
HOSTS_NEW='/etc/hosts.new'

sudo cp "$HOSTS" "$HOSTS_OLD"
sudo cp "$HOSTS" "$HOSTS_NEW"

# Search and replace patterns

OCCURS=$( sudo grep --perl-regexp "^.*	localhost$" "$HOSTS_NEW" | wc -l )
if [ "$OCCURS" -lt 1 ]; then
	# Append IP and hostname if it doesn't exist
	echo -e "127.0.0.2\tlocalhost" | sudo tee -a "$HOSTS_NEW" > /dev/null
else
	# Search and replace
	sudo sed -i 's/.*localhost$/127.0.0.2	localhost/g' "$HOSTS_NEW"
fi


OCCURS=$( sudo grep --perl-regexp "^.*	facebook.com$" "$HOSTS_NEW" | wc -l )
if [ "$OCCURS" -lt 1 ]; then
	# Append IP and hostname if it doesn't exist
	echo -e "8.8.8.8\tfacebook.com" | sudo tee -a "$HOSTS_NEW" > /dev/null
else
	# Search and replace
	sudo sed -i 's/.*facebook.com$/8.8.8.8	facebook.com/g' "$HOSTS_NEW"
fi

# Apply changes
sudo cp -f "$HOSTS_NEW" "$HOSTS"
