#!/usr/bin/env bash
#  A script that displays all active IPv4 IPs on the machine it's executed
#+ on

ifconfig | awk '/ inet / {print $2}'

#  The ``ifconfig`` command without arguments displays only active
#+ network interfaces
